if(NOT DEFINED WIKILIB_BUILD_DIR OR NOT DEFINED WIKILIB_SOURCE_DIR)
    message(FATAL_ERROR "Expected wikilib source and build directories")
endif()
set(prefix "${WIKILIB_BUILD_DIR}/tests/install-prefix")
set(consumer_build "${WIKILIB_BUILD_DIR}/tests/installed-consumer")
set(config_args)
if(TEST_CONFIG)
    list(APPEND config_args --config "${TEST_CONFIG}")
endif()
function(run_checked)
    execute_process(COMMAND ${ARGV} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Command failed (${result}): ${ARGV}\n${output}\n${errors}")
    endif()
endfunction()
run_checked("${CMAKE_COMMAND}" --install "${WIKILIB_BUILD_DIR}" --prefix "${prefix}" ${config_args})
run_checked("${CMAKE_COMMAND}" -S "${WIKILIB_SOURCE_DIR}/tests/install_consumer" -B "${consumer_build}"
    "-DCMAKE_PREFIX_PATH=${prefix}" "-DCMAKE_CXX_COMPILER=${TEST_CXX_COMPILER}"
    "-DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF" "-DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF")
run_checked("${CMAKE_COMMAND}" --build "${consumer_build}" ${config_args})
set(ctest_args)
if(TEST_CONFIG)
    list(APPEND ctest_args -C "${TEST_CONFIG}")
endif()
run_checked("${CMAKE_CTEST_COMMAND}" --test-dir "${consumer_build}" --output-on-failure ${ctest_args})
